export const ADD_FAV = 'ADD_FAV'

export const DELETE_FAV = 'DELETE_FAV'

export const FILTER_GENDER = 'FILTER_GENDER'

export const FILTER_GENDER_HOME = 'FILTER_GENDER_HOME'

export const FILTER_SPECIES_HOME = 'FILTER_SPECIES_HOME'

export const FILTER_STATUS_HOME = 'FILTER_STATUS_HOME'

export const ORDER_FAV = 'ORDER_FAV'

export const ADD_CHARACTER ='ADD_CHARACTER'

export const DELETE_CHARACTER = 'DELETE_CHARACTER'